LangString msgNodeDatadir ${LANG_SPANISH} "Establecer el lugar por los datos de blockchain"
LangString msgDatadir ${LANG_SPANISH} "Establecer el lugar por los datos de Mist"
LangString msgRegError ${LANG_SPANISH} "No se puede leer del registro. No todos los accesos directos se eliminarán"
LangString msgLeftover ${LANG_SPANISH} "Apertura de los directorios de datos restantes (Copia de seguridad antes de borrar!)"
LangString msgAdminRequired ${LANG_SPANISH} "Se requieren derechos de administrador"
